{% set version = "0.2.5.post3" %}
{% set name = "pyBioTools" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "
  entry_points:
    - pyBioTools=pyBioTools.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.6
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - tqdm>=4.51.0
    - numpy>=1.19.4
    - pysam>=0.16.0
    - pandas>=1.1.4
    - colorlog>=4.1.0

test:
  imports:
    - pyBioTools.Alignment
    - pyBioTools.Fastq
    - pyBioTools.Fasta
  commands:
    - pyBioTools Alignment -h
    - pyBioTools Fastq -h

about:
  home: https://github.com/a-slide/pyBioTools
  doc_url: https://adrienleger.com/pyBioTools/
  license: GPLv3
  licence_url: https://www.gnu.org/licenses/gpl-3.0.en.html
  summary: pyBioTools is a collection of python tools to manipulate biological sequences

extra:
  author: Adrien Leger
  author_email: aleg@ebi.ac.uk
  author_url: https://adrienleger.com
