# Required python packages to generate the documentation
# * mkdocs
# * mkdocs-material
# * pygments
# * pymdown-extensions
# * mknotebooks
# * mkdocs-exclude

# Project information
site_name: 'pyBioTools'
site_description: ''
site_author: 'Adrien Leger'
site_url: 'https://a-slide.github.io/pyBioTools/'

# Repository
repo_name: 'a-slide/pyBioTools'
repo_url: 'https://github.com/a-slide/pyBioTools'

# Copyright
copyright: 'Copyright &copy; 2019 Adrien Leger'

# Navigation menu
nav:
    - Home: index.md
    - Installation instructions: installation.md
    - Usage:
        - Alignment:
            - CLI : usage/Alignment/CLI.ipynb
            - API : usage/Alignment/API.ipynb
        - Fastq:
            - CLI : usage/Fastq/CLI.ipynb
            - API : usage/Fastq/API.ipynb
    - Citing: citing.md
    - Contributing Guidelines: contributing.md
    - Code of conduct: code_of_conduct.md
    - Licence: licence.md
    - Changelog: changelog.md

# Theme customization
theme:
    name: 'material'
    highlightjs: true
    font: false

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: a-slide
      repo: pyBioTools
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - mknotebooks
  - exclude:
      glob:
        - "usage/output/*"
        - "usage/data/*"
